### ISSUE TITLE
Feature-request: support Pointer events

### ISSUE THREAD

**Issue by limonte** [john-doherty/long-press-event#19]
First of all, thank you for the amazing plugin! It works great except for one detail: I tested it recently on Lenovo Yoga 370 which has touchscreen and `long-press` events aren't fired on that device.

The reason is that this kind of devices produce [Pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) instead of click/touch events.

My current approach is:

```diff
document.addEventListener(mouseUp, clearLongPressTimer, true);
+ document.addEventListener('pointerup', clearLongPressTimer, true);
document.addEventListener(mouseMove, mouseMoveHandler, true);
+ document.addEventListener('pointermove', mouseMoveHandler, true);
document.addEventListener('wheel', clearLongPressTimer, true);
document.addEventListener('scroll', clearLongPressTimer, true);

// hook events that can trigger a long press event
document.addEventListener(mouseDown, mouseDownHandler, true); // <- start
+ document.addEventListener('pointerdown', mouseDownHandler, true);
```

Let me know @john-doherty if this diff looks good to you, if so I can create a PR.

**Comment by catamphetamine** [comment]
@limonte I've tested it briefly in Chrome DevTools console and seems like `pointerdown` events trigger simultaneously with `mousedown` events:

```js
$1.addEventListener('mousedown', () => console.log(123), true)
$1.addEventListener('pointerdown', () => console.log(456), true)
```

Outputs:

```
123
456
```

So it's not as simple as adding an extra listener: that would also require some kind of a de-duplication.

**Comment by john-doherty** [comment]
Hi @limonte does the PR you submitted take into account @catamphetamine findings?

**Comment by catamphetamine** [comment]
@john-doherty 

@limonte 's approach seems fine: a timer is created on `pointer down` and then immediately cleared, then a new timer is created on `mouse down`.
So it seems to be a valid approach.

Perhaps also `pointer up` event should be handled somewhere there:

https://github.com/john-doherty/long-press-event/blob/fe309561c39270f36b1c289464e7240dee41d6e7/src/long-press-event.js#L119-L126

**Comment by btjones** [comment]
Hi! And thank you everyone in this thread looking into this already. Are there any updates to this? Seems this issue is a bit stale but I'm interested in support for PointerEvents. I also see a PR from @mrjestice that addresses PointerEvents.

Thanks!

**Comment by john-doherty** [comment]
Have you tested the PR to confirm this @btjones?

**Comment by btjones** [comment]
> Have you tested the PR to confirm this @btjones?

I ran into an issue when I tried the exact diff above. In my case it seemed the mouse events were firing on iOS devices when I would have expected pointer events. I also tested this PR https://github.com/john-doherty/long-press-event/pull/21 and that one seemed to work properly for me.

**Comment by john-doherty** [comment]
Thanks for confirming @catamphetamine, @btjones I've merged and published. Thanks for the PR @limonte, apologies for the delay

**Comment by limonte** [comment]
Thanks for the release @john-doherty but credits for PR are for @mrjestice :)

**Comment by john-doherty** [comment]
Ah, thanks for the correction. Big thanks for the PR @mrjestice :)

**Comment by mrjestice** [comment]
Welcome



Sent from my T-Mobile 4G LTE Device



-------- Original message --------
From: John Doherty ***@***.***>
Date: 5/24/21 1:10 PM (GMT-07:00)
To: john-doherty/long-press-event ***@***.***>
Cc: mrjestice ***@***.***>, Mention ***@***.***>
Subject: Re: [john-doherty/long-press-event] Feature-request: support Pointer events (#19)


Ah, thanks for the correction. Big thanks for the PR @mrjestice<https://github.com/mrjestice> :)
