### ISSUE TITLE
preventDefault is not working. 

### ISSUE THREAD

**Issue by JohnrBell** [john-doherty/long-press-event#24]
Prevent default is not working in this simple scenario: 

```
                var el = document.querySelectorAll('.product-item__img');
		el.forEach(function(item){
			item.addEventListener('long-press', function(e) {
			    e.preventDefault()
			    console.log(e.target);
			});
		})	
```

**Comment by john-doherty** [comment]
Please can you create a [plunker](https://plnkr.co/) so I can see this issue in action?

From a quick glance at your code, I would not create an event handler for every item. I would create a `long-press` event handler for the parent container and `e.preventDefault()` if `e.target.className.indexOf('.product-item__img') > -1`

**Comment by JohnrBell** [comment]
I've made those changes and it is working as expected.

**Comment by JohnrBell** [comment]
Unfortunately, I can't share the actual code, it's private for a client. 
I did some testing though, following your advice and it works perfectly. 
Thanks for the help!

**Comment by john-doherty** [comment]
Great to hear!
