### ISSUE TITLE
add eventlistener to dynamically added obejcts

### ISSUE THREAD

**Issue by jjoon9** [john-doherty/long-press-event#25]
in order to add eventListener to dynamically appended objects,
I tried a code below(using jQuery).

$(document).on('long-press', '.myClass', function(){
  alert('long-pressed!');
 //blabla...
});

but it does not work.

how can i deal with this problem?

I Just tried such a thing below. but this worked(on click).
$(document).on('click', '.myClass', function(){
  alert('long-pressed!');
 //blabla...
});

**Comment by john-doherty** [comment]
Not sure about JQuey, but this is how you would do it in pure JavaScript:

```js
// long-press event bubbles up the DOM, so listen at root (or parent) level
document.addEventListener('long-press', function(e) {

   // element that fired the event (this could have been injected dynamically)
   var el = e.target;

   // check if it has a specific css class name
   if (el && el.className.indexOf('myClass') > -1) {
      // do your thing
   }
});
```

**Comment by yanickhug** [comment]
@jjoon9 It worked for me on dynamically added elements.
```
$(document).on("long-press", ".detail-line-item" , function() {
	$(this).addClass('bg-primary')
	console.log('longpress')
});
```

**Comment by Isuru-Nanayakkara** [comment]
Hi @yanickhug, Is there a way to do this with vanilla JavaScript?
