### ISSUE TITLE
Long press prevents other events to fire

### ISSUE THREAD

**Issue by cosecantt** [john-doherty/long-press-event#26]
````
<script src="/js/long-press-event.min.js"></script>
<script>
    document.addEventListener('long-press', function(e) {

        // stop the event from bubbling up
        e.preventDefault()

        console.log(e.target);
    });
</script>
<div data-long-press-delay='500' click="openNote()">Note</div>

````

if I long press above div **n** times and click on it **click** event does not fire unless I click **n+1** times. The click event starts to fire from **(n+1)th** click.

**Comment by john-doherty** [comment]
Just push a fix, please can you test and reopen if this is still an issue

**Comment by john-doherty** [comment]
BTW: thank you for raising this

**Comment by cosecantt** [comment]
I have just checked and the issue still remained the same.
